name: Instagram Automation Bot

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    # Added permissions to allow the bot to save the "processed_comments" file back to GitHub
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Bot
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          KEYWORD: ${{ secrets.KEYWORD }}
          COMMENT_REPLY_TEXT: ${{ secrets.COMMENT_REPLY_TEXT }}
          DM_TEXT: ${{ secrets.DM_TEXT }}
        run: python bot.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add processed_comments.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update processed comments" && git push)
